services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${GOBID_DATABASE_NAME}
      POSTGRES_USER: ${GOBID_DATABASE_USER}
      POSTGRES_PASSWORD: ${GOBID_DATABASE_PASSWORD}
    ports:
      - ${GOBID_DATABASE_PORT:-5432}:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local