version: '3'
services:
  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "Postgres2024!"
    ports:
      - "5432:5432"
