POST http://localhost:8000/order HTTP/1.1

{
    "id":"testefinal",
    "price": 130.11,
    "tax": 0.504
}

###
GET http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json